package esprit.opportunites.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CandidatAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCandidatAllPropertiesEquals(Candidat expected, Candidat actual) {
        assertCandidatAutoGeneratedPropertiesEquals(expected, actual);
        assertCandidatAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCandidatAllUpdatablePropertiesEquals(Candidat expected, Candidat actual) {
        assertCandidatUpdatableFieldsEquals(expected, actual);
        assertCandidatUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the derived primary key is set correctly.
     *
     * @param entityToPersist the entity used to persist
     * @param persisted the persisted entity
     */
    public static void assertCandidatMapsIdRelationshipPersistedValue(Candidat entityToPersist, Candidat persisted) {
        // Validate the id for MapsId, the ids must be same
        assertThat(entityToPersist.getUser().getId()).isEqualTo(persisted.getId());
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCandidatAutoGeneratedPropertiesEquals(Candidat expected, Candidat actual) {
        assertThat(actual)
            .as("Verify Candidat auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCandidatUpdatableFieldsEquals(Candidat expected, Candidat actual) {
        assertThat(actual)
            .as("Verify Candidat relevant properties")
            .satisfies(a -> assertThat(a.getDateNaissance()).as("check dateNaissance").isEqualTo(expected.getDateNaissance()))
            .satisfies(a -> assertThat(a.getNiveauEtude()).as("check niveauEtude").isEqualTo(expected.getNiveauEtude()))
            .satisfies(a -> assertThat(a.getCvUrl()).as("check cvUrl").isEqualTo(expected.getCvUrl()))
            .satisfies(a -> assertThat(a.getStatutActuel()).as("check statutActuel").isEqualTo(expected.getStatutActuel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCandidatUpdatableRelationshipsEquals(Candidat expected, Candidat actual) {
        assertThat(actual)
            .as("Verify Candidat relationships")
            .satisfies(a -> assertThat(a.getProfil()).as("check profil").isEqualTo(expected.getProfil()))
            .satisfies(a -> assertThat(a.getDomaine()).as("check domaine").isEqualTo(expected.getDomaine()));
    }
}
