package esprit.opportunites.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DepartementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepartementAllPropertiesEquals(Departement expected, Departement actual) {
        assertDepartementAutoGeneratedPropertiesEquals(expected, actual);
        assertDepartementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepartementAllUpdatablePropertiesEquals(Departement expected, Departement actual) {
        assertDepartementUpdatableFieldsEquals(expected, actual);
        assertDepartementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepartementAutoGeneratedPropertiesEquals(Departement expected, Departement actual) {
        assertThat(actual)
            .as("Verify Departement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepartementUpdatableFieldsEquals(Departement expected, Departement actual) {
        assertThat(actual)
            .as("Verify Departement relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepartementUpdatableRelationshipsEquals(Departement expected, Departement actual) {
        assertThat(actual)
            .as("Verify Departement relationships")
            .satisfies(a -> assertThat(a.getRegion()).as("check region").isEqualTo(expected.getRegion()));
    }
}
