package esprit.opportunites.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DomaineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDomaineAllPropertiesEquals(Domaine expected, Domaine actual) {
        assertDomaineAutoGeneratedPropertiesEquals(expected, actual);
        assertDomaineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDomaineAllUpdatablePropertiesEquals(Domaine expected, Domaine actual) {
        assertDomaineUpdatableFieldsEquals(expected, actual);
        assertDomaineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDomaineAutoGeneratedPropertiesEquals(Domaine expected, Domaine actual) {
        assertThat(actual)
            .as("Verify Domaine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDomaineUpdatableFieldsEquals(Domaine expected, Domaine actual) {
        assertThat(actual)
            .as("Verify Domaine relevant properties")
            .satisfies(a -> assertThat(a.getIntitule()).as("check intitule").isEqualTo(expected.getIntitule()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDomaineUpdatableRelationshipsEquals(Domaine expected, Domaine actual) {
        // empty method
    }
}
