package esprit.opportunites.domain;

import static esprit.opportunites.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class OpportuniteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportuniteAllPropertiesEquals(Opportunite expected, Opportunite actual) {
        assertOpportuniteAutoGeneratedPropertiesEquals(expected, actual);
        assertOpportuniteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportuniteAllUpdatablePropertiesEquals(Opportunite expected, Opportunite actual) {
        assertOpportuniteUpdatableFieldsEquals(expected, actual);
        assertOpportuniteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportuniteAutoGeneratedPropertiesEquals(Opportunite expected, Opportunite actual) {
        assertThat(actual)
            .as("Verify Opportunite auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportuniteUpdatableFieldsEquals(Opportunite expected, Opportunite actual) {
        assertThat(actual)
            .as("Verify Opportunite relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()))
            .satisfies(a -> assertThat(a.getAdresse()).as("check adresse").isEqualTo(expected.getAdresse()))
            .satisfies(a -> assertThat(a.getNiveauEtudeRequis()).as("check niveauEtudeRequis").isEqualTo(expected.getNiveauEtudeRequis()))
            .satisfies(a -> assertThat(a.getNombrePostes()).as("check nombrePostes").isEqualTo(expected.getNombrePostes()))
            .satisfies(a ->
                assertThat(a.getSalaire()).as("check salaire").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSalaire())
            )
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getTypeContrat()).as("check typeContrat").isEqualTo(expected.getTypeContrat()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpportuniteUpdatableRelationshipsEquals(Opportunite expected, Opportunite actual) {
        assertThat(actual)
            .as("Verify Opportunite relationships")
            .satisfies(a -> assertThat(a.getDomaine()).as("check domaine").isEqualTo(expected.getDomaine()))
            .satisfies(a -> assertThat(a.getOrganisation()).as("check organisation").isEqualTo(expected.getOrganisation()))
            .satisfies(a -> assertThat(a.getVille()).as("check ville").isEqualTo(expected.getVille()));
    }
}
