package esprit.opportunites.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrganisationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganisationAllPropertiesEquals(Organisation expected, Organisation actual) {
        assertOrganisationAutoGeneratedPropertiesEquals(expected, actual);
        assertOrganisationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganisationAllUpdatablePropertiesEquals(Organisation expected, Organisation actual) {
        assertOrganisationUpdatableFieldsEquals(expected, actual);
        assertOrganisationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganisationAutoGeneratedPropertiesEquals(Organisation expected, Organisation actual) {
        assertThat(actual)
            .as("Verify Organisation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganisationUpdatableFieldsEquals(Organisation expected, Organisation actual) {
        assertThat(actual)
            .as("Verify Organisation relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getPresentation()).as("check presentation").isEqualTo(expected.getPresentation()))
            .satisfies(a -> assertThat(a.getSecteurActivite()).as("check secteurActivite").isEqualTo(expected.getSecteurActivite()))
            .satisfies(a -> assertThat(a.getLogoUrl()).as("check logoUrl").isEqualTo(expected.getLogoUrl()))
            .satisfies(a -> assertThat(a.getAdresse()).as("check adresse").isEqualTo(expected.getAdresse()))
            .satisfies(a -> assertThat(a.getSiteWeb()).as("check siteWeb").isEqualTo(expected.getSiteWeb()))
            .satisfies(a -> assertThat(a.getEmailContact()).as("check emailContact").isEqualTo(expected.getEmailContact()))
            .satisfies(a -> assertThat(a.getTelephone()).as("check telephone").isEqualTo(expected.getTelephone()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganisationUpdatableRelationshipsEquals(Organisation expected, Organisation actual) {
        assertThat(actual)
            .as("Verify Organisation relationships")
            .satisfies(a -> assertThat(a.getVille()).as("check ville").isEqualTo(expected.getVille()));
    }
}
