package esprit.opportunites.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfilAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilAllPropertiesEquals(Profil expected, Profil actual) {
        assertProfilAutoGeneratedPropertiesEquals(expected, actual);
        assertProfilAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilAllUpdatablePropertiesEquals(Profil expected, Profil actual) {
        assertProfilUpdatableFieldsEquals(expected, actual);
        assertProfilUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilAutoGeneratedPropertiesEquals(Profil expected, Profil actual) {
        assertThat(actual)
            .as("Verify Profil auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilUpdatableFieldsEquals(Profil expected, Profil actual) {
        assertThat(actual)
            .as("Verify Profil relevant properties")
            .satisfies(a -> assertThat(a.getIntitule()).as("check intitule").isEqualTo(expected.getIntitule()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilUpdatableRelationshipsEquals(Profil expected, Profil actual) {
        assertThat(actual)
            .as("Verify Profil relationships")
            .satisfies(a -> assertThat(a.getDomaine()).as("check domaine").isEqualTo(expected.getDomaine()));
    }
}
