package esprit.opportunites.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RecruteurAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecruteurAllPropertiesEquals(Recruteur expected, Recruteur actual) {
        assertRecruteurAutoGeneratedPropertiesEquals(expected, actual);
        assertRecruteurAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecruteurAllUpdatablePropertiesEquals(Recruteur expected, Recruteur actual) {
        assertRecruteurUpdatableFieldsEquals(expected, actual);
        assertRecruteurUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the derived primary key is set correctly.
     *
     * @param entityToPersist the entity used to persist
     * @param persisted the persisted entity
     */
    public static void assertRecruteurMapsIdRelationshipPersistedValue(Recruteur entityToPersist, Recruteur persisted) {
        // Validate the id for MapsId, the ids must be same
        assertThat(entityToPersist.getUser().getId()).isEqualTo(persisted.getId());
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecruteurAutoGeneratedPropertiesEquals(Recruteur expected, Recruteur actual) {
        assertThat(actual)
            .as("Verify Recruteur auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecruteurUpdatableFieldsEquals(Recruteur expected, Recruteur actual) {
        assertThat(actual)
            .as("Verify Recruteur relevant properties")
            .satisfies(a -> assertThat(a.getTitreProfessionnel()).as("check titreProfessionnel").isEqualTo(expected.getTitreProfessionnel())
            )
            .satisfies(a -> assertThat(a.getBiographie()).as("check biographie").isEqualTo(expected.getBiographie()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecruteurUpdatableRelationshipsEquals(Recruteur expected, Recruteur actual) {
        assertThat(actual)
            .as("Verify Recruteur relationships")
            .satisfies(a -> assertThat(a.getOrganisation()).as("check organisation").isEqualTo(expected.getOrganisation()));
    }
}
