package esprit.opportunites.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VilleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVilleAllPropertiesEquals(Ville expected, Ville actual) {
        assertVilleAutoGeneratedPropertiesEquals(expected, actual);
        assertVilleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVilleAllUpdatablePropertiesEquals(Ville expected, Ville actual) {
        assertVilleUpdatableFieldsEquals(expected, actual);
        assertVilleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVilleAutoGeneratedPropertiesEquals(Ville expected, Ville actual) {
        assertThat(actual)
            .as("Verify Ville auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVilleUpdatableFieldsEquals(Ville expected, Ville actual) {
        assertThat(actual)
            .as("Verify Ville relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVilleUpdatableRelationshipsEquals(Ville expected, Ville actual) {
        assertThat(actual)
            .as("Verify Ville relationships")
            .satisfies(a -> assertThat(a.getDepartement()).as("check departement").isEqualTo(expected.getDepartement()));
    }
}
